lexicon.txt
source/include/ota_config_defaults.h

Merge the default configuration file from the development branch into the main branch.

Add OTA default configuration file

---

source/ota.c

*Description of changes:* Fixing incorrect log flow and commas for couple of debug statements.

fixing misc errors in logging

---

source/ota_mqtt.c

Update decodeFileBlock_MQTT and requestFileBlock_MQTT to:
* Correctly use the return of the CBOR encode/decode functions.
* Correctly return an OTA error code instead of a bool.

Fix error handling of cbor calls in ota_mqtt.c

---

source/ota.c

Fix the pointer usage (compiler warnings) in job parsing.

Fix pointer usage in job parsing

---

source/include/ota.h
source/ota.c
source/portable/os/ota_os_posix.c
test/CMakeLists.txt
test/unit-test/ota_job_parsing_utest.c
test/unit-test/ota_os_posix_utest.c
test/unit-test/ota_utest.c

OTA agent:
- Initialize pal callbacks
- Fix timer in OTA suspend
Unit tests:
- OTA agent
- Job parsing
- OS POSIX timers

Fix in unit tests and OTA agent

---

source/ota.c

This change adds check to the OTA Agent task loop to exit when OTA Agent is stopped.

Add check in OTA AGent to handle shutdown

---

source/include/ota.h
source/ota_mqtt.c
source/portable/os/ota_os_freertos.c

Fix OTA FreeRTOS port 
Make topic buffers static 
Add OTA FreeRTOS port error codes

Fix OTA FreeRTOS port and other minor fixes in MQTT

---

.github/workflows/ci.yml

Add git secrets to CI checks

---

source/ota.c
test/unit-test/ota_job_parsing_utest.c

This change makes the following parameters optional - 
1. Update Filepath
2. Certificate Filepath
3. Signature 

Make filepaths and signature optional

---

.github/workflows/ci.yml
source/include/ota_config_defaults.h
source/include/ota_private.h
source/ota.c
source/ota_mqtt.c
test/unit-test/ota_config.h
test/unit-test/ota_os_posix_utest.c
test/unit-test/ota_utest.c
tools/lexicon.txt

- Improve overall unit tests coverage
- Change status update frequency into a config
- Add missing status update while receiving
- Fix bitmap memory allocation bug
- Fix a event data buffer bug in unit tests

Improve unit tests coverage

---

MISRA.md
source/include/ota_platform_interface.h
source/include/ota_private.h
source/ota.c
source/ota_http.c
tools/coverity/misra.config

Address MISRA warnings and add MISRA.md file

Address MISRA warnings and add MISRA.md file

---

source/include/ota.h
source/include/ota_http_private.h
source/include/ota_mqtt_private.h
source/ota.c
source/ota_http.c
source/ota_mqtt.c
test/unit-test/ota_utest.c

Implemented strerr functions in ota, ota_mqtt and ota_http components

Converting errors to strings

---

source/ota.c
source/ota_http.c

Added missing ; to ota_http

---

source/include/ota_private.h
source/include/stdbool.readme
source/include/stdint.readme

* Remove bool def from ota library header
* Add custom stdbool.readme file
* Add custom stdint.readme file

Remove bool def and add readme's

---

docs/doxygen/pages.dox

Replace the outdated values of the memory requirements talbe in the doxygen with the latest data based on commit a802b0772d258d771d488864712dddb12b0c6e31.

Update memory requirements table

---

README.md

Remove row with an invalid reference from README.md

Remove row with an invalid reference from README.md

---

manifest.yml

Preemptively update the coreJSON dep version

---

source/include/ota.h
source/ota.c
tools/lexicon.txt

* This change adds a self test failed event to otaAppCallback 

Add self-test failed event to otaAppCallback

---

docs/doxygen/pages.dox
source/include/ota.h
source/ota.c
test/unit-test/ota_utest.c

Renamed otaAgentTask to OTA_EventProcessingTask

---

docs/doxygen/pages.dox

Combine data test bss columns in mem req table to align with the latest format guidelines.

Combine data test bss columns in mem req table

---

source/ota.c

* Add a function for job parsing error handling , also fixes the issues with suspend/resume OTA operations.

Add job parsing error handling

---

docs/doxygen/porting.dox
tools/lexicon.txt

This PR is in preparation for https://github.com/aws/aws-iot-device-sdk-embedded-C/pull/1485 which checks for misspelled words in the Doxygen files.

Add Doxygen words to lexicon.txt and fix misspelled word.

---

source/ota_mqtt.c

* fixes bug in stringbuilder where the update status json was not getting formatted properly
* Also minor refactoring , the int to string conversions are only performed when status buffer is required . 

Fix a bug in stringbuilder for update status

---

CONTRIBUTING.md
source/include/ota_config_defaults.h

Replacing keyword master with main in docs

---

docs/doxygen/include/size_table.html
source/ota_cbor.c
test/unit-test/ota_cbor_utest.c
test/unit-test/ota_utest.c
test/unit-test/utest_helpers.c
test/unit-test/utest_helpers.h
tools/lexicon.txt

Added tests to increase the coverage of the ota cbor component.

increase cbor ut coverage

---

docs/doxygen/include/size_table.html
source/include/ota.h
source/ota.c
source/ota_mqtt.c
test/unit-test/ota_utest.c
tools/lexicon.txt

*Description of changes:
* This change adds an unsubscribe flag to the OTA_Shutdown API and handles unsubscription based on the flag.

Add unsubscribe flag to OTA_Shutdown

---

docs/doxygen/include/size_table.html
source/ota_mqtt.c

This change removes the subscription to accepted jobs topic as it is not required being a receive reserved topic.

Remove subscribing to the accepted topic

---

source/ota.c
test/unit-test/ota_utest.c

Add unit tests for state machine handlers in ota.c. This includes changes to:
* Add unit tests for requestJobHandler
* Add unit tests for requestDataHandler
* Add unit tests for initFileHandler
* Add additional mocks
* Add the function declarations of external functions to ota_utest.c
Also includes minor changes to:
* Remove a duplicate void statement in ota.c
* Update some comments and names in ota_utest.c

Improve ota.c line and branch coverage

---

source/ota.c
source/ota_mqtt.c
tools/lexicon.txt

* Adding some debugging logs
* Fixing version log to show `major.minor.build format`

Adding logs and version display fix

---

docs/doxygen/include/size_table.html
source/include/ota.h
source/include/ota_private.h
source/ota.c
tools/lexicon.txt

* Removes custom job callback and implements it to handle using appcallback
* Handles empty job by searching execution key

Handle custom and empty job callback

---

docs/doxygen/include/size_table.html
source/ota.c
test/unit-test/ota_utest.c
tools/lexicon.txt

* Remove an unreachable branch from the otaTimerCallback function
* Add unit tests for covering all branches in the setImageStateWithReason function.

Improve the code coverage of ota.c

---

source/portable/os/ota_os_freertos.h

This change adds string.h in the OTA OS Freertos header for memcpy

Add string.h header

---

source/ota.c

This change updates the verify active job status.

update verify active job logic

---

MISRA.md
docs/doxygen/include/size_table.html
source/include/ota.h
source/ota.c
source/ota_mqtt.c
test/unit-test/ota_utest.c
tools/lexicon.txt

* Fixed mandatory and required violations in `handleCustomJob`
* Updated MISRA.md file to document Rule 2.2 violation
* Added a condition in mockAppCallbackCustomParsingFails to test new branch
* Added a suppression because the value of jobDoc.jobIdLength cannot be both lesser than 0 and greater than OTA_JOB_ID_MAX_SIZE
* Added `const` quantifiers to `pJobDocJson` and `pJobId` of structure `OtaJobDocument_t`

Fixing MISRA violations and updating MISRA.md 

---

.github/workflows/ci.yml

Up the increased line and branch coverage to 100%.

Increase the required line and branch coverage

---

LICENSE

Creating License with Github UI to show MIT banner.

Updating MIT License

---

.github/workflows/ci.yml
README.md

Add a sentance about the LTS release in the README

---

CHANGELOG.md

Improve readability of sentences in CHANGELOG, especially about the point on removing subscription from Jobs topics.

Improve readability of CHANGELOG

---

CHANGELOG.md
README.md
source/include/ota.h

Mention about GA release in CHANGELOG

Mention about GA in CHANGELOG.md

---

source/ota.c

This change updates the order in which the app callback is called and the job status is updated.

Change update status and app callback order

---

source/ota.c
source/portable/os/ota_os_posix.c

*Description of changes:* The change updates log levels fro some of the logs which were not actually error logs when parsing a job document. This was confusing after successful job updates or when no jobs are in queue.

Change log level for parsing logs

---

source/include/ota.h
source/include/ota_appversion32.h
source/include/ota_base64_private.h
source/include/ota_cbor_private.h
source/include/ota_config_defaults.h
source/include/ota_http_interface.h
source/include/ota_http_private.h
source/include/ota_interface_private.h
source/include/ota_mqtt_interface.h
source/include/ota_mqtt_private.h
source/include/ota_os_interface.h
source/include/ota_platform_interface.h
source/include/ota_private.h
test/CMakeLists.txt

* Add guards for C++ linkage
* Make possible to override CMake C Standard for tests

Adding C++ guards

---

.gitmodules
test/cbmc/proofs/Makefile-project-defines
test/cbmc/proofs/Makefile-project-targets
test/cbmc/proofs/Makefile-project-testing
test/cbmc/proofs/Makefile.common
test/cbmc/proofs/README.md
test/cbmc/proofs/prepare.py
test/cbmc/proofs/run-cbmc-proofs.py

In this PR, I have added the infrastructure required for the development of the CBMC proofs. The files added in this PR are based on that. The files changed is only the .gitmodules in which I haved `updata=none` to it. This PR is also in sync with the main 

Add CBMC-proofs infrastructure

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/ci.yml

Adding a Pull request template
Description
-----------
* Add a template for PRs
* Update contributing guidelines
Checklist:
----------

Adding a Pull request template

---

source/ota.c
source/ota_mqtt.c

Description
-----------
Fix build warnings.

Fix build warnings

---

source/include/ota_config_defaults.h

Description
-----------
Remove non-ASCII characters

Remove non-ASCII characters

---

source/include/ota_config_defaults.h
source/include/ota_private.h

Description
-----------
Make OTA file type configurable

Make OTA file type configurable

---

test/cbmc/proofs/validateAndStartJob/Makefile
test/cbmc/proofs/validateAndStartJob/README.md
test/cbmc/proofs/validateAndStartJob/cbmc-proof.txt
test/cbmc/proofs/validateAndStartJob/cbmc-viewer.json
test/cbmc/proofs/validateAndStartJob/validateAndStartJob_harness.c

Add CBMC proof of validateAndStartJob function
Description
-----------
This PR adds files required for the CBMC proof of validateAndStartJob function.
Checklist:
----------

Add CBMC proof of validateAndStartJob

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/documentation-issue.md
.github/ISSUE_TEMPLATE/feature-request.md

Description
-----------
This PR adds issue templates which makes it easier and clearer for the users to create appropriate posts.
Checklist:
----------

Add Issue templates to the repository

---

.gitmodules
README.md
test/cbmc/proofs/Makefile-template-defines
test/cbmc/proofs/Makefile.common
test/cbmc/proofs/OTA_Suspend/Makefile
test/cbmc/proofs/Posix_OtaReceiveEvent/Makefile
test/cbmc/proofs/Posix_OtaReceiveEvent/Posix_OtaReceiveEvent_harness.c
test/cbmc/proofs/Posix_OtaSendEvent/Makefile
test/cbmc/proofs/Posix_OtaSendEvent/Posix_OtaSendEvent_harness.c
test/cbmc/proofs/README.md
test/cbmc/proofs/lib/summarize.py
test/cbmc/proofs/run-cbmc-proofs.py
tools/lexicon.txt

Description
-----------
This PR:
- changes the SPDX identifier in a single CBMC proof's Makefile
- introduces updates to the files related to the CBMC starter kit (this was accomplished by running `cbmc-starter-kit-update`).
- removes 2 .git submodules (this was accomplished by running `cbmc-starter-kit-update --remove-starter-kit-submodule --remove-litani-submodule`). symlinks to files present in the CBMC starter-kit submodule are no longer present Additionally, a user will have to install litani (instructions [here](https://github.com/awslabs/aws-build-accumulator#installation)) in order to run CBMC proofs locally. litani is present in the CI system that executes the CBMC proofs.
- updates the `README` to include a section on CBMC.
Checklist:
----------
Changes pertain to CBMC proofs, …

Update CBMC starter kit

---

.github/workflows/release.yml
manifest.yml

Description
-----------
Checklist:
----------

Add license information for dependencies in manifest.yml file.

---

docs/doxygen/include/size_table.md
source/ota.c

Print string with length check
Description
-----------
As #491 mentioned, that reads might more than expected.
Submit the change to read the string with limited length.
Checklist:
----------

Print string with length check

---

README.md

Description
-----------
Add readme section explaining our long term
direction with this repository.
Checklist:
----------

Update README for coreOTA libraries launch
