source/ota_mqtt.c
Update OTA code to correctly check for a boolean true on success when calling OTA_CBOR_Encode_GetStreamRequestMessage or OTA_CBOR_Decode_GetStreamResponseMessage.
=> Fix incorrect conditionals for cbor return values

source/include/ota.h, source/ota_mqtt.c
Make it so that decodeFileBlock_Mqtt and requestFileBlock_Mqtt return a proper OTA error.
=> Fix cbor error handling in ota_mqtt.c

source/ota_mqtt.c
Update OTA code to correctly check for a boolean true on success when calling OTA_CBOR_Encode_GetStreamRequestMessage or OTA_CBOR_Decode_GetStreamResponseMessage.
=> Update incorrect ota mqtt conditionals

source/ota_mqtt.c
Fix an issue where the asserts where checking the size of the pointer instead of the size of the buffer. 
=> Fix asserts for snprintf results in ota mqtt

source/ota_interface.c
This change add include for the missing assert header.
=> Add missing assert header in ota interface

source/ota_mqtt.c
Cherry-pick a fix for the asserts in ota_mqtt.c from development to main.
Co-authored-by: Tiangang Song <ts.whu@outlook.com>
=> Fix asserts for snprintf results in ota mqtt (#66)

source/include/ota.h, source/include/ota_interface_private.h, source/include/ota_mqtt_private.h, source/include/ota_private.h, source/ota.c, source/ota_mqtt.c
- Fix include of stdbool.h
- decodeFileBlock should accept const network buffer
- decodeFileBlock_mqtt should not reuse network buffer
- remove unused methods
- signature buffer should not be dynamically allocated
- only update http url when it's not NULL
- decoded data payload should be freed after processDataBlock
=> Bug fixes in #88

source/include/ota.h, source/include/ota_platform_interface.h, source/ota.c, test/unit-test/ota_utest.c, tools/lexicon.txt
OTA PAL error codes are composed inside PAL implementation, thus PAL interface should return uint32_t error codes (combined with main and sub) instead.
**Notes:**
- `otaconfigMAX_NUM_REQUEST_MOMENTUM` is removed from `OtaErrMomentumAbort` because it's directly returned from state machine handler and not reported to the cloud. We will print this error, so composing here is unnecessary and will cause confusing when reading the log error message.
- Default wait time in OTA unit tests is increased to 2s since it seems too short for `test_OTA_ReceiveFileBlockComplete` test.
=> Fix PAL error codes

source/include/ota_mqtt_interface.h, source/ota_mqtt.c, test/unit-test/ota_utest.c
This change removes the unnecessary round trip for mqtt callbacks and updates the OTA mqtt interface definition.
=> Remove callbacks from OTA mqtt interface

source/include/ota_private.h, tools/lexicon.txt
The event data structure was updated incorrectly and this change restores the bufferused member in it.
=> Add back bufferUsed to event data stuct

.github/workflows/release-workflow.yml
Release automation for OTA.
**Release automation**
**Add a GitHub Action job to trigger a release process** which includes operations of: 
1. Creating and pushing the release tag to the repository 
2. Verifying the pushed tag (performing a diff with the commit ID which is tagged) 
3. Creating a ZIP for the release asset. 
4. Verifying the ZIP by performing a diff check and running unit tests on the unzipped files.
5. Creating a release on the repository for the tag, and uploading the ZIP as the release asset
*Testing*
**Release Automation**
The workflow can be manually triggered and takes the input values of **Commit ID** (to create a release for) and the **Version string** for tagging the release with
Test run of the GHA run on my fork …
=> GHA: Release automation.

test/unit-test/ota_os_posix_utest.c
Remove this statement in favor of tracking the issue internally.
=> Remove TODO statement from ota_os_posix_utest.c

.github/workflows/ci.yml, source/include/ota_mqtt_interface.h
*Description*:
Fixes a typo resulting in the following warning from doxygen:
```
warning: argument 'ucQoS' of command @param is not found in the argument list of OtaMqttPublish_t(const char *const pacTopic, uint16_t usTopicLen, const char *pcMsg, uint32_t ulMsgSize, uint8_t ucQos)
```
=> Fix doxygen warning

test/unit-test/CMakeLists.txt, test/unit-test/ota_utest.c, tools/cmock/coverage.cmake
The ota.c file has a static global variable and a number of static functions that need to be accessed for unit testing. 
This change is to run sed before building to generate a temporary file that is a copy of the original ota.c, but the static keyword has been removed. This temporary file is generated in the build directory and is used in place of the original for building. The coverage report generation was also updated to check the code coverage of this temporary file instead of the original.
=> Remove static from ota.c before running unit tests

.github/memory_statistics_config.json, .github/workflows/ci.yml, .github/workflows/memory_statistics.yml, docs/doxygen/config.doxyfile, docs/doxygen/include/size_table.html, docs/doxygen/pages.dox
Adds A PR check to check if the sizes in the doxygen documentation are up to date.
Additionally adds a manual workflow to generate the size table.
=> Add size table to PR checks

source/ota.c, test/unit-test/ota_utest.c
The unit tests were intermittently failing due to timing issues. This PR fixes these timing issues by removing multithreading from the ota.c unit tests.
=> Stabilize the ota.c unit tests

.github/workflows/ci.yml, tools/cmock/coverage.cmake
The git actions workflow for gathering the code coverage data was building with the `-DCMAKE_BUILD_TYPE=Release` flag enabled. This flag was causing optimizations to be enabled which altered the coverage data. Due to these optimizations, some of the code was considered covered when it wasn't and vice versa.
This update is to change the build flag so that it doesn't have optimizations enabled. This causes the line coverage to go down in some of the files, but after investigating the dips, these are all correct and reflect the coverage of the code accurately.
=> Update coverage workflow to build with the debug flag

docs/doxygen/include/size_table.html, source/ota.c
The change clears the self-test flag.
=> clear self-test flag

source/include/ota_private.h, source/ota.c, test/unit-test/ota_utest.c, tools/lexicon.txt
Fix error handling in code for ingesting blocks:
* Replaced NULL checks for pointers to static variables with asserts.
* Added a check for receiving a data block event from the application that has NULL data.
* Add a unit test for receiving a null data block.
=> Update error handling for processing data blocks

source/ota_http.c, source/ota_interface.c, source/ota_mqtt.c, test/unit-test/CMakeLists.txt
fsanitizer causes the coverage tools to track more branches than expected. This was originally introduced when the unit-tests were multi-threaded and can be removed now.
=> Disable fsanitizer from unit-test

.github/workflows/ci.yml
Use python 3.7.10 for memory estimator check.
=> Use python 3.7.10 for memory estimator check

source/ota.c, test/unit-test/ota_utest.c, tools/lexicon.txt
Add unit tests for ota.c
* Add a test for closing a NULL file pointer
* Update and test memory handling for data block buf 
* Remove delay and fix the incorrect shutdown tests
* Exclude two lines in OTA_Shutdown from branch cov.
* Test calling shutdownHandler with NULL interfaces
* Change if check to an assert in executeHandler
* Test receiving a data block and failing to send it
* Add more tests for user inputs to OTA_Init
* Test activating a new image with a null PAL function
=> Add unit tests for ota.c

source/include/ota_config_defaults.h, source/ota.c
*Description of changes:* This change adds -
* A new configuration in the OTA config to set the file type id for firmware files
* A check on the file type as firmware before performing version check 
=> Add check for filetype id before doing version check

.github/workflows/ci.yml, docs/doxygen/pages.dox, tools/lexicon.txt
Equivalent of https://github.com/aws/Jobs-for-AWS-IoT-embedded-sdk/pull/39 in OTA library documentation about handling both custom and OTA jobs in application.
=> Add note in documentation on handling OTA and custom jobs

test/unit-test/ota_utest.c, tools/lexicon.txt
* verifyActiveJobStatus uses the data protocol interface to
cleanup after receiving a new unrelated job document. Test
that it safely handles cleaning up while the protocol
interface is NULL.
=> Test a NULL interface with verifyActiveJobStatus

source/portable/os/ota_os_freertos.c
This change sets the OTA lib timer callback in OTA freeRTOS port.
=> Register OTA time callback in ota freeRTOS port

source/ota.c, tools/lexicon.txt
*Description of changes:* Fixes the version strings in logs for new/old image
=> Fix the version strings in logs for new/old image

CHANGELOG.md, source/ota.c
*Issue #, if available:* #199
This change adds a cast when logging size_t type .
=> Add cast for size_t while logging 

source/include/ota_os_interface.h, source/ota.c, test/unit-test/ota_os_posix_utest.c, test/unit-test/ota_utest.c, tools/lexicon.txt
*Issue:*
[Build error in C ++ projects issue](https://github.com/aws/ota-for-aws-iot-embedded-sdk/issues/201)
Changing the OS name of methods for working with timers for a successful build by the C ++ compiler (rename delete to deleteTimer)
=> Renaming OS timer methods ()

source/include/ota_os_interface.h, source/ota.c, test/unit-test/ota_os_posix_utest.c, test/unit-test/ota_utest.c, tools/lexicon.txt
Reverting the pull request  aws/ota-for-aws-iot-embedded-sdk#202 as this is interface change which breaks the LTS APIs and the OTA demos.
Another follow up PR will be created to handle issue with C++ build.
=> Revert "Renaming OS timer methods ()"

source/include/ota_platform_interface.h
* This macro merges a main error and a sub error. When it was doing this
merge, it was not masking the sub error. This meant that it could
impact the main error if the sub error was too large.
=> Fix the bitmask in the OTA_PAL_COMBINE_ERR macro

source/ota_mqtt.c
Resolves: https://github.com/aws/ota-for-aws-iot-embedded-sdk/issues/208
The number of received blocks in the message was always equal to the total number of blocks because the same value was used twice. I have changed the denominator value to the right one.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution under the terms of your choice.
=> Fix the MQTT status message "receiving"

source/include/ota.h
Resolves: https://github.com/aws/ota-for-aws-iot-embedded-sdk/issues/210
Remove the false statement that the application callback is optional. The application callback is required and never checked for NULL. There is also no default callback in the code.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution under the terms of your choice.
=> Fix misleading documentation of the OtaAppCallback_t

source/include/ota.h, source/ota.c
Resolves: https://github.com/aws/ota-for-aws-iot-embedded-sdk/issues/212
The library does not modify the contents of the OtaInterfaces_t instance provided by the user. Therefore, the pOtaInterface pointer should be a pointer to a constant instance of the structure.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution under the terms of your choice.
=> Make pOtaInterface a pointer to const

source/portable/os/ota_os_posix.c
'S_IRWXU' undeclared when compiling ota_demo_core_mqtt
add sys/stat.h head file
=> fix error: 'S_IRWXU' undeclared

source/include/ota_private.h, source/portable/os/ota_os_freertos.c, test/unit-test/ota_utest.c
*Description of changes:* This pull request includes two changes - 
1. Remove old macro definition for OTA_NUM_MSG_Q_ENTRIES and its use in the freertos ota port.
2. Fix the queue buffer size in the freertos ota port.
=> Remove old reference for message queue and fix the queue buffer size

source/ota.c
*Description of changes:* The app callback should be moved after populating the contents in jobDoc so that it is available as data to application.
=> Move app callback after populating the jobDoc var

source/portable/os/ota_os_freertos.c
The change removes unnecessary assert in the ota freertos port which was throwing compiler warning as the comparison is always true.
=> Fix compiler warning due to unnessary config assert

source/include/ota_os_interface.h, tools/lexicon.txt
The member in the OTA OS timer interface was incorrectly named as deleted which breaks the C++ builds. This change conditionally renames delete timer for C++ builds.
=> Conditionally rename delete timer for C++ builds.

test/cbmc/proofs/Makefile-project-defines
This pull request updates the CBMC proof infrastructure to use the latest version of the aws-templates-for-cbmc-proofs submodule (the starter kit).  The prior version was from July and the computation of proof_root in run-cbmc-proofs.py changed in late July in commit 6a361dcb of aws-templates-for-cbmc-proofs.
This pull request also sets the include paths in Makefile-project-defines to the include directories needed to build the goto binaries.
=> Update CBMC proof infrastructure

source/portable/os/ota_os_posix.c
posix: Cast timer_t to (void *) before assigning to sigevent.sigev_value.sival_ptr
Description
-----------
sigevent.sigev_value.sival_ptr is of type (void *) per POSIX spec.
Currently the codes assign otaTimers[ otaTimerId ] (type timer_t) to
it without any casting.
The POSIX spec does not clearly define what type timer_t should be so
it seems to be an implementation specific type. On platforms like Linux
with glibc the timer_t is (void *) but on some other platforms this
might be an integer, like in VxWorks it is unsigned long. On such
platforms it unfortunately creates a warning during build:
warning: incompatible integer to pointer conversion assigning to
'void *' from 'timer_t' (aka 'unsigned long') [-Wint-conversion]
sgEvent.sigev_value.sival_ptr = otaTimers[ otaTimerId ];
Casting …
=> posix: Cast timer_t to (void *) before assigning to sigevent.sigev_value.sival_ptr

otaFilePaths.cmake
3rdparty: Specify C99 compiler flag for tinycbor source files
Description
-----------
The tinycbor codes use several macros from C99 math.h, like
FP_INFINITE, FP_NAN, INFINITE, NAN. Although it currently builds
fine with -std=gnu90 against Linux glibc, it fails to build with
a stricter C library.
Specify C99 compiler flag for tinycbor source files.
This relates to https://github.com/aws/aws-iot-device-sdk-embedded-C/pull/1748
Checklist:
----------
=> 3rdparty: Specify C99 compiler flag for tinycbor source files

source/ota.c
Since `pParamAdd` is only used when the `docParam.modelParamType` is set to either `ModelParamTypeStringCopy` or `ModelParamTypeArrayCopy`, the assignment statement should be moved to a proper scope to avoid  having undefined values in `pParamAdd` 
Description
-----------
This PR updates the changes the location of the `pParamAdd` assignment to a proper scope. 
Checklist:
----------
=> Update scope of pParamAdd

docs/doxygen/include/size_table.md, source/include/ota.h, source/include/ota_private.h, source/ota.c, test/unit-test/ota_utest.c, tools/lexicon.txt
For certain values of the file size of the firmware, some statements in the OTA library may result in an arithmetic overflow. 
Description
-----------
Add conditional statements in order to avoid arithmetic overflow in some operations. 
Checklist:
----------
=> Add checks to avoid arithmetic overflow

.github/workflows/ci.yml, .gitmodules
Git should not automatically clone the submodules as customers likely do not need them. In projects and hub repos submoduling this library, in the current state recursive clones will pull in multiple copies of tinycbor, coreJSON, FreeRTOS kernel, etc when they have their own copies. After this change, recursive clones will no longer get these submodules (unless user specifies --checkout).
=> Add "update = none" to submodules

source/ota.c, test/cbmc/proofs/ingestDataBlock/ingestDataBlock_harness.c, test/cbmc/proofs/processDataHandler/processDataHandler_harness.c
Moves the clearing of otaAgent.pActiveJobName to after OtaAppCallback is called in order to enable the callback to access the job name.
=> Move cleanup of job id to after OtaAppCallback

docs/doxygen/include/size_table.md, source/ota_mqtt.c, test/unit-test/ota_utest.c
The change adds a condition to send status update when first block is received.
Description
-----------
Checklist:
----------
=> Send status update on first block received.

source/include/ota.h, source/ota.c, test/cbmc/proofs/handleCustomJob/Makefile, test/cbmc/proofs/handleJobParsingError/Makefile, test/cbmc/proofs/handleJobParsingError/handleJobParsingError_harness.c, test/cbmc/proofs/handleSelfTestJobDoc/Makefile, test/cbmc/proofs/handleUnexpectedEvents/Makefile, test/cbmc/proofs/inSelfTestHandler/Makefile, test/cbmc/proofs/parseJobDoc/Makefile, test/cbmc/proofs/processDataHandler/Makefile, test/cbmc/proofs/processJobHandler/Makefile, test/unit-test/ota_utest.c, tools/lexicon.txt
Add no active job event in application callback
Description
-----------
This change adds a new event in application callback. This provides a callback when no active job is available in service to process. Useful in cases where device needs to shutdown OTA agent if no active jobs are available to save power.
Checklist:
----------
=> Add new event for application callback when no active jobs are available

otaDependenyFilePaths.cmake, otaFilePaths.cmake, test/CMakeLists.txt, test/unit-test/CMakeLists.txt
Decouple build dependency with coreJSON and tinyCBOR.
Description
-----------
Create otaDependenyFilePaths.cmake to handle dependency files path.
Seperate them to decouple OTA library dependency with TinyCBOR and coreJSON.
Checklist:
----------
=> Decouple build dependency with coreJSON and tinyCBOR.

source/include/ota_private.h, source/ota.c, test/cbmc/proofs/decodeAndStoreKey/decodeAndStoreKey_harness.c, tools/lexicon.txt
change default signature size to 384 to support RSA-3072
Description
-----------
As mentioned in #238, change default signature size to 384 to support RSA-3072.
Checklist:
----------
=> change default signature size to 384 tto support RSA-3072

source/ota.c, test/cbmc/proofs/OTA_Resume/Makefile, test/cbmc/proofs/OTA_Resume/OTA_Resume_harness.c, test/unit-test/ota_utest.c
Description
-----------
Fix bug detailed in issue #421 and add test coverage for the changes.
Test Bed
-----------
| Component | Version |
| ------- | ----- |
| Platform | esp32-devkitc |
| OTA library | latest:main |
| CSDK | latest:main |
For integration tests, I modified the [OTA MQTT](https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/main/demos/ota/ota_demo_core_mqtt) demo provided by the csdk. Test application initializes/starts OTA agent, then calls `OTA_Resume` while no OTAs are pending or in flight.
[Integration Test Logs (Before)](https://github.com/aws/ota-for-aws-iot-embedded-sdk/files/8875827/before.txt)
[Integration Test Logs (After)](https://github.com/aws/ota-for-aws-iot-embedded-sdk/files/8875867/after.txt)
Note my added logs containing "Int-Test". Before the fix, …
=> Bug Fix: OTA_Resume only restarts selftest timer while selftesting

docs/doxygen/include/size_table.md, source/include/ota.h, source/ota.c, test/cbmc/proofs/OTA_EventProcess/Makefile, test/cbmc/proofs/OTA_EventProcess/OTA_EventProcess_harness.c, test/cbmc/proofs/OTA_EventProcess/README.md, test/cbmc/proofs/OTA_EventProcess/cbmc-proof.txt, test/cbmc/proofs/OTA_EventProcess/cbmc-viewer.json, test/unit-test/ota_utest.c, tools/lexicon.txt
Description
-----------
Some users may not want to spawn a new thread just to run ota agent. To accommodate, a single-cycle function has been added that effectively runs a single iteration of the loop in `OTA_EventProcessingTask`.
Currently `OtaAgentStateReady` is used by the library to know when the ota processor task has started. This notion of task readiness is retained with the new function, where the agent is not `OtaAgentStateReady` until the `OTA_EventProcess` has been called for the first time in it's new, user defined, daemon.
State is returned from `OTA_EventProcess` as a potential for users to react to, or perhaps log, the ota agent state upon `OTA_EventProcess` return. 
Caveats
-----------
Unfortunately, the library does not provide thread sync mechanisms in its PAL OSAL, so …
=> Feature: Add user callable agent cycler

docs/doxygen/include/size_table.md, source/include/ota.h, source/include/ota_config_defaults.h, source/ota.c, source/portable/os/ota_os_freertos.c, test/cbmc/proofs/OTA_Init/Makefile, test/cbmc/proofs/OTA_Init/OTA_Init_harness.c, test/cbmc/proofs/OTA_Shutdown/Makefile, test/cbmc/proofs/OTA_Shutdown/OTA_Shutdown_harness.c, test/cbmc/proofs/OtaReceiveEvent_FreeRTOS/OtaReceiveEvent_FreeRTOS_harness.c, test/cbmc/proofs/agentShutdownCleanup/Makefile, test/cbmc/proofs/agentShutdownCleanup/agentShutdownCleanup_harness.c, test/cbmc/proofs/resetEventQueue/Makefile, test/cbmc/proofs/resetEventQueue/README.md, test/cbmc/proofs/resetEventQueue/cbmc-proof.txt, test/cbmc/proofs/resetEventQueue/cbmc-viewer.json, test/cbmc/proofs/resetEventQueue/resetEventQueue_harness.c, test/unit-test/ota_utest.c, tools/lexicon.txt
Keep event/callback functions pointer in OTA_Shutdown to avoid accessing NULL pointer.
Description
-----------
For #218 , we need a method to make sure there is no NULL function pointer.
1. Check if OTA initialized in public API OTA_SignalEvent and OTA_EventProcessingTask.
2. Do not erase the functions pointer, pOtaInterface and OtaAppCallback, in OTA_Shutdown.
3. Only create event queue in the first OTA_Init() --> so we don't need to deinit it for #217 
4. Only change the OTA state in task running OTA_EventProcessingTask. --> fix #219 
Checklist:
----------
=> Keep event/callback functions pointer in OTA_Shutdown to avoid accessing NULL pointer.

source/include/ota.h, source/ota.c, test/unit-test/ota_utest.c
Add more description on OtaAppCallback_t to help user get familiar with it sooner, and remove const property on pData to avoid misunderstanding.
Description
-----------
- Add more description on OtaAppCallback_t to help user get familiar with it faster.
- Remove const property on pData to avoid misunderstanding.
- As #220 mentioned, pData is used for memory management in demo, but we declared it as const may make users misunderstand it. So, remove the property.
Checklist:
----------
=> Add more description on OtaAppCallback_t and remove const property on pData.

source/ota.c
Remove assertion check to make out-of-order packet work
Description
-----------
Cloud may send the out-of-order (index) OTA packets.
Because we've checked the index in function validateDataBlock(), we don't need to check it again here.
And we shouldn't assume the lastest index packet must be the lastest coming packets.
Checklist:
----------
=> Remove assertion check to make out-of-order packet work

source/include/ota_appversion32.h, source/include/ota_config_defaults.h
Make appFirmwareVersion const configurable
Description
-----------
The appFirmwareVersion cannot be const in some cases when the version is stored in a secure element, for example, the PSA (Platform Security Architecture) API cannot be used for OTA if the appFirmwareVersion is declared as const. 
We propose to make it configurable with a define. The default case will be const, but if necessary it can be changed, without modifying the code. 
Checklist:
----------
=> Make appFirmwareVersion const configurable

source/ota.c, source/ota_mqtt.c
Description
-----------
A simple OTA update may produce hundreds of lines
of logs just for marking the progress of the update
stream, data block by data block.
All OTA stream data block LogInfo messages are
changed to LogDebug messages.
The OTA update stream still shows forward progress.
A LogInfo message is emitted for every 32 data blocks received.
Checklist:
----------
=> Reduce verbosity of OTA update logs

test/cbmc/proofs/resumeHandler/resumeHandler_harness.c
Signed-off-by: Felipe R. Monteiro <felisous@amazon.com>
Description
-----------
Fix type-checking issue in the memory safety proof for `resumeHandler`.
Checklist:
----------
=> Fix typing issue on resumeHandler proof

source/ota.c, source/portable/os/ota_os_freertos.c, source/portable/os/ota_os_posix.c
Description
-----------
Remove CR and LF character from logging calls.
Newline characters are highly platform dependent, so should be handled in the logging macro defined by the integrator of the OTA library.
Checklist:
----------
- [ X ] I have tested my changes. No regression in existing tests.
- [ X ] My code is formatted using Uncrustify.
- [ X ] I have read and applied the rules stated in CONTRIBUTING.md. 
=> Remove \r\n from logging statements.

docs/doxygen/include/size_table.md, source/include/ota_config_defaults.h, source/ota_mqtt.c, test/cbmc/proofs/OTA_Init/Makefile, test/cbmc/proofs/requestJob_Mqtt/Makefile, test/cbmc/proofs/requestJob_Mqtt/requestJob_Mqtt_harness.c, test/cbmc/source/strnlen.c, test/cbmc/stubs/strnlen.c, test/unit-test/ota_utest.c, tools/lexicon.txt
Description
-----------
Updated the `ThingName` maximum length to 128 characters. This matches the documented AWS IoT Core length limit. Because of this change, the ThingName will be truncated to 53 characters maximum when added to the `ClientToken` field.
Testing:
---------
1. Pulled changes to Ubuntu 22.04 Ec2 instance
2. Followed unit test instructions.
3. Unit tests passed. Output below...
```
Test project /home/ubuntu/ota-for-aws-iot-embedded-sdk/build
Start 1: ota_utest
1/4 Test #1: ota_utest ........................   Passed    0.02 sec
Start 2: ota_base64_utest
2/4 Test #2: ota_base64_utest .................   Passed    0.00 sec
Start 3: ota_cbor_utest
3/4 Test #3: ota_cbor_utest ...................   Passed    0.00 sec
Start 4: ota_os_posix_utest
4/4 Test #4: ota_os_posix_utest …
```
=> Update ThingName to a maximum of 128 characters

README.md, test/cbmc/proofs/requestJob_Mqtt/Makefile, test/cbmc/proofs/requestJob_Mqtt/requestJob_Mqtt_harness.c
Description
-----------
* Adds readme section describing CBMC local execution
* Corrects mispelling of 'pieces'
* Adds comment explaining thingname size bounds
Checklist:
----------
- [N/A] I have tested my changes. No regression in existing tests.
- [N/A] My code is formatted using Uncrustify.
- [ x ] I have read and applied the rules stated in CONTRIBUTING.md. 
=> Update readme for CBMC local runs

source/ota_mqtt.c, test/unit-test/ota_utest.c
Description
-----------
Previously the stringBuilder method would return
and empty string when the integer value of '0' was supplied. With this change, the string representation "0" is returned.
Checklist:
----------
- [ x ] I have tested my changes. No regression in existing tests.
- [ x ] My code is formatted using Uncrustify.
- [ x ] I have read and applied the rules stated in CONTRIBUTING.md. 
=> Fix stringBuilderUInt32Decimal to handle 0 value

docs/doxygen/include/size_table.md, source/ota.c, test/unit-test/ota_utest.c
Add a check into the parseJobDoc() function to see if the OTA transfer will require more blocks than the bitmap has declared.
This pull request was created to fix #476 
=> OTA Bitmap Field Size Comparison

source/ota_mqtt.c, test/unit-test/ota_utest.c
FIX: Invalid topic used to publish request for outstanding OTA jobs
Description
-----------
From the original poster @imoir:
> This looks like a regression in commit https://github.com/aws/ota-for-aws-iot-embedded-sdk/commit/e43672a0881d6aad65df3a61ece5a4e019c3559f, the thing name is not added to the topic parts in function requestJob_Mqtt() in source/ota_mqtt.c.
fix #480 
Checklist:
----------
=> FIX: Invalid topic used to publish request for outstanding OTA jobs

source/ota.c, source/ota_cbor.c, source/ota_mqtt.c, source/portable/os/ota_os_freertos.c, source/portable/os/ota_os_posix.c
This fixes assumptions that int32_t is defined as int and so on.
Printf parameters were also otherwise not cast to the type specifiers used in the format strings.
These can cause warnings and failed compilations.
=> Fix assumptions on definitions of fixed width types

source/include/ota_config_defaults.h, source/include/ota_private.h
Add public config option for OTA bitmap size
Description
-----------
This adds a public config option to override an existing private option.
This commit has no functional changes.
Checklist:
----------
=> Add public config option for OTA bitmap size

.github/workflows/ci.yml, README.md, docs/doxygen/include/size_table.md, source/include/ota.h, source/include/ota_private.h, source/ota.c, test/cbmc/proofs/getFileContextFromJob/getFileContextFromJob_harness.c, test/cbmc/proofs/parseJobDoc/parseJobDoc_harness.c, test/cbmc/proofs/processJobHandler/processJobHandler_harness.c, test/cbmc/proofs/verifyRequiredParamsExtracted/verifyRequiredParamsExtracted_harness.c, test/unit-test/ota_utest.c, tools/lexicon.txt
Description
-----------
Rough pass on handling empty job document errors. An empty job document will only contain the `clientToken` and `timestamp` fields which currently causes an issue.
Related issue - https://github.com/aws/ota-for-aws-iot-embedded-sdk/issues/482
Checklist:
----------
=> Empty job fix

.github/workflows/ci.yml, CHANGELOG.md, MISRA.md, test/cbmc/proofs/OTA_Init/Makefile, test/cbmc/proofs/OtaStopTimer_FreeRTOS/Makefile, test/cbmc/proofs/executeHandler/Makefile, test/cbmc/proofs/ingestDataBlock/Makefile, test/cbmc/proofs/otaClose/Makefile, test/cbmc/proofs/processDataHandler/Makefile, test/cbmc/proofs/requestJob_Mqtt/Makefile, test/cbmc/proofs/setImageStateWithReason/Makefile, test/cbmc/proofs/startHandler/Makefile, test/cbmc/proofs/verifyActiveJobStatus/Makefile, tools/lexicon.txt
Fixing Whitespace check bug in action.yml
Description
-----------
The formatting action had a bug causing the job to never run and then return a pass. One part of this is handled by this FreeRTOS/CI-CD-GitHub-Actions#63. The other part is handled in this PR, also fixed the trailing whitespace in files that had it.
Checklist:
----------
=> Fixing Whitespace check bug in action.yml

test/unit-test/ota_utest.c
Description
-----------
Fixing test cases by explicitly setting
pContext pointer to NULL for later check.
Testing
-----------
Checked out OTA package, built unit tests, observed two failing tests.
Build commands:
```
cmake -S test -B build
make -C build all
cd build && ctest
```
Previously failing tests:
```
Test project /home/kstribrn/workspace/ota-for-aws-iot-embedded-sdk/build
Start 1: ota_utest
1/4 Test #1: ota_utest ........................***Failed    0.02 sec
Start 2: ota_base64_utest
2/4 Test #2: ota_base64_utest .................   Passed    0.00 sec
Start 3: ota_cbor_utest
3/4 Test #3: ota_cbor_utest ...................   Passed    0.00 sec
Start 4: ota_os_posix_utest
4/4 Test #4: ota_os_posix_utest ...............   Passed    5.01 sec
75% tests passed, 1 tests failed out of 4 …
```
=> Explicitly set pointer to NULL

README.md
Fix Unit Test Instructions In Readme
Description
-----------
Missing dependency in submodule initialisation.
Added linux as a dependency for building. Using `mqueue.h` is not portable. I can't figure out if this is a posix issue or a macOS issue, but the effect is the same regardless. I can't see any Windows specific code and I pretty sure Windows is not posix compliant.
Checklist:
----------
=> Fix Unit Test Instructions In Readme

README.md, source/include/ota_config_defaults.h
Description
-----------
Checklist:
----------
=> Fix broken links
